// generating a random number 
var randomNumber;


// These will memorize the count of the number of levels 
var NumberOfLevels = 1;

// this is the array which will hold the value of the class of the buttons
var arr = ["green", "red", "yellow", "blue"];

// this will store the pattern generated by the game 
var gameGeneratedSeq = [];

// this will store the pattern generated by the user 
var userGeneratedSeq = [];

var shit = false;

// this is the start of the game or the entry point of the game 
$(document).keypress(function () {
    if (!shit) {
        $("h1").text("Level " + NumberOfLevels);
        generatesequence();
        shit = true;
    }
});

// this will get the input from the mouse click and will check using the function 
$(".btn").click(function () {
    if(shit){
    var chosencolor = $(this).attr("id");
    userGeneratedSeq.push(chosencolor);
    animate(chosencolor)
    let audio = new Audio(chosencolor + ".mp3");
    audio.play();
    $("#" + chosencolor).addClass("pressed");
    setTimeout(() => {
        $("#" + chosencolor).removeClass("pressed");
    }, 100);
    checkanswer(userGeneratedSeq.length - 1);
}
})

function checkanswer(levelrightnow) {

    // these if are the reason that the user can input the no of keys of the pattern 
    // first if check wether the element at the top of the userGeneratedSeq is similar to that particular index of the gameGeneratedSeq
    // second if check if the length of the pattern entered by the user is similar ot the game geneartedseq 

    if (userGeneratedSeq[levelrightnow] === gameGeneratedSeq[levelrightnow]) {
        if (userGeneratedSeq.length === gameGeneratedSeq.length) {
            NumberOfLevels++;
            // this will start the next newsequence after some interval of time that is 1s 
            setTimeout(() => {
            generatesequence();
            }, 1000);
        }
        }
    
    else {
        $("body").addClass("game-over");
        setTimeout(() => {
            $("body").removeClass("game-over");
        }, 100);
        let audio = new Audio("wrong.mp3");
        audio.play();
        startOver();
        $("h1").text("Game Over, Press Any Key to Restart");
    }

}

function generatesequence() {

    // this will reset the user generatesequence that will be entered after every time the use will be entering the remeberd sequence 
    userGeneratedSeq = [];
    $("h1").text("Level " + NumberOfLevels);
    
    // this will generate the new number that 
    randomNumber = Math.floor(Math.random(randomNumber) * 4);

    var chosencolorr = arr[randomNumber]
    // this will give the animation of flash to the button 
    $("#"+chosencolorr).fadeOut(100).fadeIn(100);

    let audio = new Audio(arr[randomNumber] + ".mp3");
    audio.play();

    // this will push the passed element to the top of the aray 
    gameGeneratedSeq.push(chosencolorr);

}

function animate(chosencolor){
    $("#" + chosencolor).fadeOut(100).fadeIn(100);
}

// this will start the game from zero after loosing 

function startOver() {
    NumberOfLevels = 1;
    userGeneratedSeq = [];
    gameGeneratedSeq = [];
    shit = false;
}